name: wordpress_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.6.4+7

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.4
  dots_indicator: ^2.1.0
  google_fonts: ^3.0.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  http: ^0.13.4
  jiffy: ^5.0.0
  path_provider: ^2.0.10
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  skeleton_text: ^3.0.0
  timeago: ^3.2.2
  firebase_core: ^1.17.0
  firebase_messaging: ^11.4.0
  rounded_loading_button: ^2.1.0
  flutter_svg: ^1.0.3
  url_launcher: ^6.1.2
  share: ^2.0.4
  launch_review: ^3.0.1
  package_info: ^2.0.2
  easy_localization: ^3.0.1
  animated_bottom_navigation_bar: ^0.3.3
  flutter_web_browser: ^0.17.1
  flare_flutter: ^3.0.2
  fluttertoast: ^8.0.9
  google_mobile_ads: ^1.2.0
  loading_indicator: ^3.1.0
  flutter_html: ^3.0.0-alpha.3
  better_player: ^0.0.82
  firebase_analytics: ^9.1.8
  flutter_math_fork: ^0.6.2
  youtube_player_iframe: ^2.2.2
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
  md2_tab_indicator:
    git:
      url: https://github.com/westdabestdb/md2_tab_indicator
  firebase_auth:
  firebase_auth_web:
  firebase_auth_platform_interface: 6.1.10
  webview_flutter: ^2.0.8
dependency_overrides:
  firebase_core_platform_interface: 4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

    

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/translations/
    - assets/animation_files/

  fonts:

    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 400
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800




